-- ==========================================
-- SUPABASE COMPLETE MASTER SETUP (V12 - HARDENED SECURITY)
-- ==========================================

-- 1. Setup Custom Type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
        CREATE TYPE public.user_role AS ENUM ('guest', 'staff', 'receptionist', 'manager', 'admin');
    END IF;
END $$;

-- 2. Core Operational Tables

-- Profiles
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users ON DELETE CASCADE,
  full_name TEXT,
  email TEXT UNIQUE,
  role public.user_role DEFAULT 'guest',
  avatar_url TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Rooms
CREATE TABLE IF NOT EXISTS public.rooms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price DECIMAL(10,2) NOT NULL,
  image_url TEXT,
  is_popular BOOLEAN DEFAULT false,
  is_top_tier BOOLEAN DEFAULT false,
  features TEXT[] DEFAULT '{}',
  gallery TEXT[] DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Reservations (Room Bookings)
CREATE TABLE IF NOT EXISTS public.reservations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users ON DELETE SET NULL,
  guest_name TEXT,
  room_name TEXT,
  total_amount DECIMAL(10,2),
  check_in DATE,
  check_out DATE,
  status TEXT DEFAULT 'Pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Dining Reservations
CREATE TABLE IF NOT EXISTS public.dining_reservations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users ON DELETE SET NULL,
  guest_name TEXT,
  venue_name TEXT,
  guests_count INTEGER,
  reservation_time TEXT,
  special_requests TEXT,
  status TEXT DEFAULT 'Pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Event Inquiries
CREATE TABLE IF NOT EXISTS public.event_inquiries (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users ON DELETE SET NULL,
  guest_name TEXT,
  event_type TEXT,
  guests_count INTEGER,
  status TEXT DEFAULT 'Pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tasks
CREATE TABLE IF NOT EXISTS public.tasks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  category TEXT,
  priority TEXT,
  status TEXT DEFAULT 'Assigned',
  reporter_id UUID REFERENCES auth.users ON DELETE SET NULL,
  reporter_name TEXT,
  assigned_to_name TEXT,
  room_number TEXT,
  task_time TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Staff Requests
CREATE TABLE IF NOT EXISTS public.staff_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  staff_id UUID REFERENCES auth.users ON DELETE CASCADE,
  staff_name TEXT,
  staff_role TEXT,
  request_text TEXT,
  status TEXT DEFAULT 'Pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Room Reviews
CREATE TABLE IF NOT EXISTS public.room_reviews (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  room_id BIGINT REFERENCES public.rooms(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users ON DELETE SET NULL,
  guest_name TEXT NOT NULL,
  rating INTEGER CHECK (rating >= 1 AND rating <= 5),
  comment TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Staff Invites
CREATE TABLE IF NOT EXISTS public.staff_invites (
  email TEXT PRIMARY KEY,
  role public.user_role NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Dining Venues
CREATE TABLE IF NOT EXISTS public.dining_venues (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  hours TEXT,
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Menu Items
CREATE TABLE IF NOT EXISTS public.menu_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id BIGINT REFERENCES public.dining_venues ON DELETE CASCADE,
  category TEXT,
  subcategory TEXT,
  name TEXT NOT NULL,
  description TEXT,
  price TEXT,
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Event Venues
CREATE TABLE IF NOT EXISTS public.event_venues (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  capacity INTEGER,
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. HARDENED SECURITY & RLS POLICIES

-- Enable RLS on all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reservations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dining_reservations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_inquiries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.room_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff_invites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dining_venues ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_venues ENABLE ROW LEVEL SECURITY;

-- Helper Function to check if user is staff/admin
CREATE OR REPLACE FUNCTION public.is_staff()
RETURNS BOOLEAN AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid()
    AND role IN ('staff', 'receptionist', 'manager', 'admin')
  );
$$ LANGUAGE sql SECURITY DEFINER;

-- Profiles Policies
DROP POLICY IF EXISTS "Public profiles are viewable by everyone" ON public.profiles;
CREATE POLICY "Public profiles are viewable by everyone" ON public.profiles FOR SELECT USING (true);
DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Rooms Policies
DROP POLICY IF EXISTS "Rooms are viewable by everyone" ON public.rooms;
CREATE POLICY "Rooms are viewable by everyone" ON public.rooms FOR SELECT USING (true);
DROP POLICY IF EXISTS "Only staff can modify rooms" ON public.rooms;
CREATE POLICY "Only staff can modify rooms" ON public.rooms FOR ALL USING (public.is_staff());

-- Reservations Policies
DROP POLICY IF EXISTS "Users can view own reservations" ON public.reservations;
CREATE POLICY "Users can view own reservations" ON public.reservations FOR SELECT USING (auth.uid() = user_id OR public.is_staff());
DROP POLICY IF EXISTS "Anyone can create a reservation" ON public.reservations;
CREATE POLICY "Anyone can create a reservation" ON public.reservations FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Only staff can update reservations" ON public.reservations;
CREATE POLICY "Only staff can update reservations" ON public.reservations FOR UPDATE USING (public.is_staff() OR auth.uid() = user_id);

-- Tasks Policies
DROP POLICY IF EXISTS "Staff can view and manage tasks" ON public.tasks;
CREATE POLICY "Staff can view and manage tasks" ON public.tasks FOR ALL USING (public.is_staff());

-- Staff Requests Policies
DROP POLICY IF EXISTS "Staff can view and manage their requests" ON public.staff_requests;
CREATE POLICY "Staff can view and manage their requests" ON public.staff_requests FOR ALL USING (public.is_staff());

-- Room Reviews Policies
DROP POLICY IF EXISTS "Reviews are viewable by everyone" ON public.room_reviews;
CREATE POLICY "Reviews are viewable by everyone" ON public.room_reviews FOR SELECT USING (true);
DROP POLICY IF EXISTS "Authenticated users can post reviews" ON public.room_reviews;
CREATE POLICY "Authenticated users can post reviews" ON public.room_reviews FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);

-- Other Catalog tables (Dining, Events, Menu)
DROP POLICY IF EXISTS "Catalog is viewable by everyone" ON public.dining_venues;
CREATE POLICY "Catalog is viewable by everyone" ON public.dining_venues FOR SELECT USING (true);
DROP POLICY IF EXISTS "Catalog is viewable by everyone" ON public.menu_items;
CREATE POLICY "Catalog is viewable by everyone" ON public.menu_items FOR SELECT USING (true);
DROP POLICY IF EXISTS "Catalog is viewable by everyone" ON public.event_venues;
CREATE POLICY "Catalog is viewable by everyone" ON public.event_venues FOR SELECT USING (true);

-- 4. Grant API access
GRANT ALL ON ALL TABLES IN SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO postgres, anon, authenticated, service_role;

-- 5. Setup Signup Trigger
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  assigned_role public.user_role;
BEGIN
  -- Check if the email is invited to a specific role
  SELECT role INTO assigned_role FROM public.staff_invites WHERE email = new.email;

  -- Fallback to guest if not invited
  IF assigned_role IS NULL THEN
    assigned_role := 'guest'::public.user_role;
  END IF;

  INSERT INTO public.profiles (id, email, full_name, role)
  VALUES (new.id, new.email, COALESCE(new.raw_user_meta_data->>'full_name', 'Guest'), assigned_role);
  RETURN NEW;
EXCEPTION WHEN OTHERS THEN RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 6. INITIAL SEED DATA
INSERT INTO public.rooms (name, description, price, features, image_url, is_popular)
VALUES
('Standard King', 'A serene escape featuring artisanal textures and a signature King-sized mattress.', 180, ARRAY['WiFi', 'Climate Control', 'Service'], 'https://lh3.googleusercontent.com/aida-public/AB6AXuDFrpyURkjBqTpsTRQpX2-9-zX-hrs3IWU3r3dX6GOIJMRp3e2kY9L5f1Pay5fGDWzf1XhGNIL-pBuoW7-_77M1hhNgAy3ob_6T3zIqm-9SWKitblQ8JmBh82y87PDNXSNT5lq2rK2NCRelYpTOJU2BdgV7-7GH-X8sr490Vco2vg3ZFBvju7WEnsS3P6wlFngfuyc4zlc1N6ByO0LT8ViXD6I2eyFzh9LlWp8gdtkQefzKhWFbJhZRUgUeTA7vNdvMvRxrjB3UqYze', true),
('Deluxe Suite', 'Extended living spaces with panoramic views of the Kigali hills.', 320, ARRAY['Complimentary Airport Shuttle', 'Luxury Bathing Amenities'], 'https://lh3.googleusercontent.com/aida-public/AB6AXuCGD8oZOP6zoeRii_iKG8cj-JldLoCoz_MZM0R6pFI7kUBEk9wSmgdhkyLX2I7lhAf16zYaytzY1CSeHgRpVfhPESii4CCrFlqbhGp5Wi9BdXFToNvL1WV_NTxBConRxM3aWiiHlcvqZEkoHBJJvoTIfiivIcuY9tteks8_bn_dxA8N6Gnf22XcxVRDRB5v0WnGYTV7jd5SmdMi64BT-DOODRCaS915r-J5Fy0ZRlbdDU3NjB4LiQkjT2YsoCWUn19UAYB815ZSuWd5', false),
('Executive Penthouse', 'The ultimate expression of luxury. 24/7 personal butler service.', 1200, ARRAY['Personal Butler', 'Private Terrace', 'Premium Bar'], 'https://lh3.googleusercontent.com/aida-public/AB6AXuBWPfF7IR_DRXEuineYUYowxsJuAn6BAnxQb0vc5MmRMlMK4UaozSp1Gt2hm3FH9bcyyJcRZtQ4h6I5gBoPmofbB4figYECbyFZZ8mAkBO9wxdIfvRh5gH54U4dpM9SqAWXOrLaZHiLIAe0t_OK5l2L1_dSRqqIyPFys116B6TPJtrmPqBimQrLiFAB7df-D9NuVXo6g_EgVHT5Axil1CU5jKVShZlg9hdwYXM5tK4OOTyGp9v_6C2KGuOl0240bQNexZkwyqbSEQ6p', true)
ON CONFLICT DO NOTHING;

-- Force Cache Refresh
NOTIFY pgrst, 'reload schema';
