-- ==========================================
-- SUPABASE COMPLETE MASTER SETUP (V9)
-- ==========================================

-- 1. Setup Custom Type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
        CREATE TYPE public.user_role AS ENUM ('guest', 'staff', 'receptionist', 'manager', 'admin');
    END IF;
END $$;

-- 2. Create All Tables
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users ON DELETE CASCADE,
  full_name TEXT,
  email TEXT UNIQUE,
  role public.user_role DEFAULT 'guest',
  avatar_url TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.rooms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price DECIMAL(10,2) NOT NULL,
  image_url TEXT,
  is_popular BOOLEAN DEFAULT false,
  is_top_tier BOOLEAN DEFAULT false,
  features TEXT[] DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.staff_invites (
  email TEXT PRIMARY KEY,
  role public.user_role NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.reservations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users ON DELETE SET NULL,
  guest_name TEXT,
  room_name TEXT,
  total_amount DECIMAL(10,2),
  check_in DATE,
  check_out DATE,
  status TEXT DEFAULT 'Pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.event_venues (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  capacity INTEGER,
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.dining_venues (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  hours TEXT,
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.menu_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id BIGINT REFERENCES public.dining_venues ON DELETE CASCADE,
  category TEXT,
  subcategory TEXT,
  name TEXT NOT NULL,
  description TEXT,
  price TEXT,
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.dining_reservations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users ON DELETE SET NULL,
  guest_name TEXT,
  venue_name TEXT,
  guests_count INTEGER,
  reservation_time TEXT,
  special_requests TEXT,
  status TEXT DEFAULT 'Pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.event_inquiries (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users ON DELETE SET NULL,
  guest_name TEXT,
  event_type TEXT,
  guests_count INTEGER,
  status TEXT DEFAULT 'Pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.tasks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  category TEXT,
  priority TEXT,
  status TEXT DEFAULT 'Assigned',
  reporter_id UUID REFERENCES auth.users ON DELETE SET NULL,
  reporter_name TEXT,
  assigned_to_name TEXT,
  room_number TEXT,
  task_time TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.staff_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  staff_id UUID REFERENCES auth.users ON DELETE CASCADE,
  staff_name TEXT,
  staff_role TEXT,
  request_text TEXT,
  status TEXT DEFAULT 'Pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Open All Permissions & RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Profiles ALL" ON public.profiles;
CREATE POLICY "Profiles ALL" ON public.profiles FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.rooms ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Rooms ALL" ON public.rooms;
CREATE POLICY "Rooms ALL" ON public.rooms FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.event_venues ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Events ALL" ON public.event_venues;
CREATE POLICY "Events ALL" ON public.event_venues FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.dining_venues ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Dining ALL" ON public.dining_venues;
CREATE POLICY "Dining ALL" ON public.dining_venues FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.menu_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Menu ALL" ON public.menu_items;
CREATE POLICY "Menu ALL" ON public.menu_items FOR ALL USING (true) WITH CHECK (true);

-- Enable all others with permissive ALL
ALTER TABLE public.reservations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Res ALL" ON public.reservations;
CREATE POLICY "Res ALL" ON public.reservations ALL USING (true);

ALTER TABLE public.dining_reservations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "DiningRes ALL" ON public.dining_reservations;
CREATE POLICY "DiningRes ALL" ON public.dining_reservations ALL USING (true);

ALTER TABLE public.event_inquiries ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Event ALL" ON public.event_inquiries;
CREATE POLICY "Event ALL" ON public.event_inquiries ALL USING (true);

ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Tasks ALL" ON public.tasks;
CREATE POLICY "Tasks ALL" ON public.tasks ALL USING (true);

ALTER TABLE public.staff_requests ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "StaffReq ALL" ON public.staff_requests;
CREATE POLICY "StaffReq ALL" ON public.staff_requests ALL USING (true);

ALTER TABLE public.staff_invites ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Invites ALL" ON public.staff_invites;
CREATE POLICY "Invites ALL" ON public.staff_invites ALL USING (true);

-- 4. Grant API access
GRANT USAGE ON SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO postgres, anon, authenticated, service_role;

-- 5. Setup Signup Trigger
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, role)
  VALUES (new.id, new.email, COALESCE(new.raw_user_meta_data->>'full_name', 'Guest'), 'guest'::public.user_role);
  RETURN NEW;
EXCEPTION WHEN OTHERS THEN RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 6. INITIAL SEED DATA
INSERT INTO public.rooms (name, description, price, features, image_url, is_popular)
VALUES
('Standard King', 'A serene escape featuring artisanal textures and a signature King-sized mattress.', 180, ARRAY['WiFi', 'Climate Control', 'Service'], 'https://lh3.googleusercontent.com/aida-public/AB6AXuDFrpyURkjBqTpsTRQpX2-9-zX-hrs3IWU3r3dX6GOIJMRp3e2kY9L5f1Pay5fGDWzf1XhGNIL-pBuoW7-_77M1hhNgAy3ob_6T3zIqm-9SWKitblQ8JmBh82y87PDNXSNT5lq2rK2NCRelYpTOJU2BdgV7-7GH-X8sr490Vco2vg3ZFBvju7WEnsS3P6wlFngfuyc4zlc1N6ByO0LT8ViXD6I2eyFzh9LlWp8gdtkQefzKhWFbJhZRUgUeTA7vNdvMvRxrjB3UqYze', true),
('Deluxe Suite', 'Extended living spaces with panoramic views of the Kigali hills.', 320, ARRAY['Complimentary Airport Shuttle', 'Luxury Bathing Amenities'], 'https://lh3.googleusercontent.com/aida-public/AB6AXuCGD8oZOP6zoeRii_iKG8cj-JldLoCoz_MZM0R6pFI7kUBEk9wSmgdhkyLX2I7lhAf16zYaytzY1CSeHgRpVfhPESii4CCrFlqbhGp5Wi9BdXFToNvL1WV_NTxBConRxM3aWiiHlcvqZEkoHBJJvoTIfiivIcuY9tteks8_bn_dxA8N6Gnf22XcxVRDRB5v0WnGYTV7jd5SmdMi64BT-DOODRCaS915r-J5Fy0ZRlbdDU3NjB4LiQkjT2YsoCWUn19UAYB815ZSuWd5', false),
('Executive Penthouse', 'The ultimate expression of luxury. 24/7 personal butler service.', 1200, ARRAY['Personal Butler', 'Private Terrace', 'Premium Bar'], 'https://lh3.googleusercontent.com/aida-public/AB6AXuBWPfF7IR_DRXEuineYUYowxsJuAn6BAnxQb0vc5MmRMlMK4UaozSp1Gt2hm3FH9bcyyJcRZtQ4h6I5gBoPmofbB4figYECbyFZZ8mAkBO9wxdIfvRh5gH54U4dpM9SqAWXOrLaZHiLIAe0t_OK5l2L1_dSRqqIyPFys116B6TPJtrmPqBimQrLiFAB7df-D9NuVXo6g_EgVHT5Axil1CU5jKVShZlg9hdwYXM5tK4OOTyGp9v_6C2KGuOl0240bQNexZkwyqbSEQ6p', true)
ON CONFLICT DO NOTHING;
